Fix GCC8 warnings:
In function 'qubesdb_insert.part.0',
    inlined from 'qubesdb_insert':
db-core.c:91:9: error: 'strncpy' specified bound 64 equals destination size [-Werror=stringop-truncation]
         strncpy(new_entry->path, path, QDB_MAX_PATH);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
db-core.c: In function 'qubesdb_add_watch':
db-core.c:165:5: error: 'strncpy' specified bound 64 equals destination size [-Werror=stringop-truncation]
     strncpy(new_watch->path, path, QDB_MAX_PATH);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
db-core.c: In function 'qubesdb_fire_watches':
db-core.c:216:13: error: 'strncpy' specified bound 64 equals destination size [-Werror=stringop-truncation]
             strncpy(hdr.path, path, sizeof(hdr.path));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit 50c2e728b6de8e8f737eb1681f88e5931d95f876)