python: fix gcc -Wsign-compare warnings
Specifically:
    qubesdb.c: In function ‘qdbpy_list’:
    qubesdb.c:174:23: error: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Werror=sign-compare]
             for (i = 0; i < list_len; i++) {
                           ^
    qubesdb.c: In function ‘qdbpy_multiread’:
    qubesdb.c:217:23: error: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Werror=sign-compare]
             for (i = 0; i < list_len; i++) {
                           ^
    qubesdb.c: In function ‘parse_handle_path’:
    qubesdb.c:412:23: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
         if (strlen(*path) != path_len) {
                           ^~
    cc1: all warnings being treated as errors

Fixes QubesOS/qubes-issues#5217

(cherry picked from commit af25aa2ee3e635a1070b6ed821c120acc9e72c9a)